name: Build & Publish Debug APK

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #  https://github.com/actions/setup-java
    - name: Set up AWS Corretto JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '17'
        architecture: x64
    - name: Get latest code
      uses: actions/checkout@v4
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Releasing using Hub
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
